##
## tgunzip  -  gzip decompressor example
##
## GCC makefile (Linux, FreeBSD, BeOS and QNX)
##
## Copyright (c) 2003 by Joergen Ibsen / Jibz
## All Rights Reserved
##
## http://www.ibsensoftware.com/
##

target  = tgunzip
objects = tgunzip.o
libs    = ../../lib/libtinf.a

cflags  = -s -Wall -Os -I../../src
ldflags = $(cflags)

.PHONY: all clean

all: $(target)

$(target): $(objects)
	gcc $(ldflags) -o $@ $^ $(libs)

%.o : %.c
	gcc $(cflags) -c $<

clean:
	$(RM) $(objects) $(target)
